### ISSUE TITLE
# TitleAVAIL

### ISSUE THREAD

**Issue by jmclifton** [gtalarico/aec-startups#23] opened 2019-05-14 17:56 UTC
# Title
Konstru

# Description
Version control for Structures

# Website
Version control for Structures

# Image
logos/konstru.png

# Crunchbase
https://www.crunchbase.com/organization/konstru

# Industries
* engineering

Tags:
* web-app

**Comment by gtalarico** [comment] 2019-05-21 20:57
Duplicate of #24

**Closed** 2019-05-21 20:57 UTC
